/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.dbsti.aula.view;

import br.com.dbsti.aula.controller.CantorController;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author DBS
 */
public class CantorFrame extends javax.swing.JFrame {

    /**
     * Creates new form CantorFrame
     */
    public CantorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoesPnl = new javax.swing.JPanel();
        opcoesPnl = new javax.swing.JPanel();
        novoBtn = new javax.swing.JButton();
        salvarBtn = new javax.swing.JButton();
        excluirBtn = new javax.swing.JButton();
        camposPnl = new javax.swing.JPanel();
        fotoPnl = new javax.swing.JPanel();
        fotoLbl = new javax.swing.JLabel();
        nomelbl = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        sobreNomeLbl = new javax.swing.JLabel();
        sobrenomeTxt = new javax.swing.JTextField();
        carregarFotoBtn = new javax.swing.JButton();
        tabelaPnl = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filtrosPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeFiltroTxt = new javax.swing.JTextField();
        pesquisarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cantor");
        setName("CantorFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 400));

        botoesPnl.setPreferredSize(new java.awt.Dimension(400, 400));

        opcoesPnl.setBackground(new java.awt.Color(102, 102, 102));
        opcoesPnl.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        novoBtn.setText("Novo");
        novoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoBtnActionPerformed(evt);
            }
        });
        opcoesPnl.add(novoBtn);

        salvarBtn.setText("Salvar");
        salvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBtnActionPerformed(evt);
            }
        });
        opcoesPnl.add(salvarBtn);

        excluirBtn.setText("Excluir");
        opcoesPnl.add(excluirBtn);

        camposPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fotoPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));

        javax.swing.GroupLayout fotoPnlLayout = new javax.swing.GroupLayout(fotoPnl);
        fotoPnl.setLayout(fotoPnlLayout);
        fotoPnlLayout.setHorizontalGroup(
            fotoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );
        fotoPnlLayout.setVerticalGroup(
            fotoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nomelbl.setText("Nome");

        sobreNomeLbl.setText("Sobrenome");

        carregarFotoBtn.setText("Carregar Foto");
        carregarFotoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarFotoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout camposPnlLayout = new javax.swing.GroupLayout(camposPnl);
        camposPnl.setLayout(camposPnlLayout);
        camposPnlLayout.setHorizontalGroup(
            camposPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camposPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(camposPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(camposPnlLayout.createSequentialGroup()
                        .addComponent(nomelbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeTxt))
                    .addGroup(camposPnlLayout.createSequentialGroup()
                        .addComponent(sobreNomeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sobrenomeTxt))
                    .addGroup(camposPnlLayout.createSequentialGroup()
                        .addComponent(carregarFotoBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        camposPnlLayout.setVerticalGroup(
            camposPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(camposPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(camposPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(camposPnlLayout.createSequentialGroup()
                        .addGroup(camposPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomelbl)
                            .addComponent(nomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(camposPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sobreNomeLbl)
                            .addComponent(sobrenomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(carregarFotoBtn))
                    .addComponent(fotoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabelaPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaPnl.setViewportView(jTable1);

        filtrosPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome");

        pesquisarBtn.setText("Pesquisar");

        javax.swing.GroupLayout filtrosPnlLayout = new javax.swing.GroupLayout(filtrosPnl);
        filtrosPnl.setLayout(filtrosPnlLayout);
        filtrosPnlLayout.setHorizontalGroup(
            filtrosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filtrosPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeFiltroTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisarBtn)
                .addContainerGap())
        );
        filtrosPnlLayout.setVerticalGroup(
            filtrosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filtrosPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filtrosPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeFiltroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout botoesPnlLayout = new javax.swing.GroupLayout(botoesPnl);
        botoesPnl.setLayout(botoesPnlLayout);
        botoesPnlLayout.setHorizontalGroup(
            botoesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(opcoesPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(filtrosPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabelaPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
            .addComponent(camposPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botoesPnlLayout.setVerticalGroup(
            botoesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botoesPnlLayout.createSequentialGroup()
                .addComponent(filtrosPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camposPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcoesPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botoesPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(botoesPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(808, 634));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtnActionPerformed
        controller.salvar();
    }//GEN-LAST:event_salvarBtnActionPerformed

    private void novoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoBtnActionPerformed
        controller.novo();
    }//GEN-LAST:event_novoBtnActionPerformed

    private void carregarFotoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarFotoBtnActionPerformed
        JFileChooser selecionador = new JFileChooser();
        int opcao = selecionador.showOpenDialog(this);
        if (opcao == JFileChooser.APPROVE_OPTION) {
            File foto = selecionador.getSelectedFile();
            controller.carregarFoto(foto);
        }
    }//GEN-LAST:event_carregarFotoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CantorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CantorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CantorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CantorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CantorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botoesPnl;
    private javax.swing.JPanel camposPnl;
    private javax.swing.JButton carregarFotoBtn;
    private javax.swing.JButton excluirBtn;
    private javax.swing.JPanel filtrosPnl;
    private javax.swing.JLabel fotoLbl;
    private javax.swing.JPanel fotoPnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomeFiltroTxt;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JLabel nomelbl;
    private javax.swing.JButton novoBtn;
    private javax.swing.JPanel opcoesPnl;
    private javax.swing.JButton pesquisarBtn;
    private javax.swing.JButton salvarBtn;
    private javax.swing.JLabel sobreNomeLbl;
    private javax.swing.JTextField sobrenomeTxt;
    private javax.swing.JScrollPane tabelaPnl;
    // End of variables declaration//GEN-END:variables
    private CantorController controller = new CantorController(this);
        
    public String getNome() {
        return nomeTxt.getText();
    }

    public String getSobrenome() {
        return sobrenomeTxt.getText();
    }
    
    public void mostraMensagem(String msn){
        JOptionPane.showMessageDialog(this, msn);
    }

    public void limpaCampos() {
        nomeTxt.setText(null);
        sobrenomeTxt.setText(null);
    }

    public void setFoto(ImageIcon icone) {
        fotoLbl.setIcon(icone);
    }
}
